version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ../wordpress:/var/www/html
      - ../nginx/log:/var/log/nginx
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - WORDPRESS_DB_PASSWORD=PASSWORD
    links:
      - wordpress:php

  wordpress:
    image: wordpress:4.9.1-fpm
    volumes:
      - ../wordpress:/var/www/html
      - ../php/php.ini:/usr/local/etc/php/php.ini:ro
      - ../php/log:/var/log/php
    links:
      - mysql:mysql

  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD

  phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   links:
    - mysql
   ports:
    - 8282:80
   environment:
    PMA_HOST: mysql
    PMA_PORT: "3306"
    MYSQL_ROOT_PASSWORD: PASSWORD
